/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.mshri.gradlelab;


import java.io.BufferedReader;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

public class App {

    private static final Logger log = LogManager.getLogger(App.class);

    public static void main(String[] args) {
        log.info("App started");
        log.info("Testing exception...");
        testException();
    }

    public static void testException(){
        try {
            int k = 5;
            log.info("Calling tryException with " + Integer.toString(k));
            // int x = MyUtil.tryException(k);
            // log.info("tryException returned " + Integer.toString(x));
            String s = MyUtil.tryException(k);
            log.info("tryException returned " + s);
            int y = s.length();
            log.info("Value of Y is " + Integer.toString(y));
        } catch (Exception e) {
            log.error(e.getMessage());
        }
    }


    public static void testLogging(){
        log.info("log4j Info message.");
    }

    public static void testingErrorLogging(){
        MyUtil.testError("Testing error logging, no error");
    }

    public static void testProps(){
        System.out.println(String.format("Name: %s\nRepo: %s", Config.getProperty("name"), Config.getProperty("repo")));
        System.out.println(String.format("Env: %s", Config.getProperty("env")));
    }

    public static void tesMail(){
        try {
            MyUtil.sendEmail("Test simple java mail", "Hello!", false, "mshrinetra@outlook.com, imsakshisingh26@gmail.com; crazymanvendra@gmail.com;", null, null, null, null);
    
            String mailTemplateFile = "C:\\Users\\mshri\\SandBox\\gradlelab\\app\\src\\main\\resources\\mail_template.html";
            BufferedReader br = new BufferedReader(new FileReader(mailTemplateFile));
            String mailTemplate = br.lines().collect(Collectors.joining());;

            List<MailEmbedObject> embedObjs = new ArrayList<MailEmbedObject>();
            embedObjs.add(new MailEmbedObject("test-embed-img-one","C:\\Users\\mshri\\SandBox\\gradlelab\\devref\\one.jpeg"));
            embedObjs.add(new MailEmbedObject("test-embed-img-two","C:\\Users\\mshri\\SandBox\\gradlelab\\devref\\two.jpeg"));
            embedObjs.add(new MailEmbedObject("test-embed-img-three","C:\\Users\\mshri\\SandBox\\gradlelab\\devref\\three.jpeg"));

            MyUtil.sendEmail("Test embed java mail", mailTemplate, true, "mshrinetra@outlook.com", "imsakshisingh26@gmail.com; crazymanvendra@gmail.com;", null, embedObjs, "C:\\Users\\mshri\\SandBox\\gradlelab\\devref\\10000 Records.csv;C:\\Users\\mshri\\SandBox\\gradlelab\\devref\\10000 Records.prn");
            br.close();

        } catch (Exception e) {
            System.out.println("Error in sending mail");
        }
    }
}
