/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.mshri.gradlelab;

public class App {
    public static void main(String[] args) {
        MyUtil.printMsg("First changes in dev branch.");
    }
}
