/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.mshri.gradlelab;


import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

public class App {

    private static final Logger log = LogManager.getLogger(App.class);

    public static void main(String[] args) {
        MyUtil.printMsg("First changes in dev branch.");

        System.out.println(String.format("Name: %s\nRepo: %s", Config.getProperty("name"), Config.getProperty("repo")));

        log.info("log4j Info message.");

        MyUtil.testError("Testing error logging, no error");
    }
}
